name: SmartBear Supported Issue Label Added

on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pact-foundation/.github/.github/workflows/triage.yml@master
    secrets: inherit
