name: Add new issues to triage board

on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - labeled
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/pact-foundation/projects/16
          github-token: ${{ secrets.TRIAGE_PROJECT_ISSUE_TOKEN }}
          # If needed, can use 
          # labeled: bug, needs-triage
          # label-operator: OR
  add-to-project-classic:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-location: pact-foundation
          project-number: 17
          column-name: New Issue
          issue-number: ${{ github.event.number }}

